import { describe, it, expect, vi, afterEach } from 'vitest';
import { createTestHarness, parseToolResult } from '@chrischall/mcp-utils/test';
import { registerHealthcheckTools } from '../src/tools/healthcheck.js';
import type { ResolvedAuth } from '../src/auth.js';

/**
 * A CDN/WAF block is not a rejected credential (mcp-host#1015).
 *
 * mcp-utils 2.9.0's credential healthcheck reports a CDN/WAF refusal page as
 * `edge_blocked`, but it can only see the page if the error the probe throws
 * carries some of it. These run the REAL client against the page CloudFront
 * serves, so they fail if anything between the response and the healthcheck
 * drops the markers the shared classifier reads.
 */

// CloudFront's block page, as served (whitespace trimmed, ids made up).
const CLOUDFRONT_BLOCK =
  '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">' +
  '<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">' +
  '<TITLE>ERROR: The request could not be satisfied</TITLE></HEAD><BODY>' +
  '<H1>403 ERROR</H1><H2>The request could not be satisfied.</H2><HR noshade size="1px">' +
  'Request blocked. We can\'t connect to the server for this app or website at this time. ' +
  'There might be too much traffic or a configuration error. Try again later, or contact the app or ' +
  'website owner.<BR clear="all"><HR noshade size="1px"><PRE>Generated by cloudfront (CloudFront)\n' +
  'Request ID: AbCdEfGhIjKlMnOpQrStUvWxYz0123456789abcdefghijklmnopqr==</PRE><ADDRESS></ADDRESS></BODY></HTML>';

function blocked(): Response {
  return new Response(CLOUDFRONT_BLOCK, {
    status: 403,
    statusText: 'Forbidden',
    headers: { 'content-type': 'text/html', 'x-cache': 'Error from cloudfront', server: 'CloudFront' },
  });
}

interface Result {
  ok: boolean;
  error?: { kind: string; message: string };
}

async function healthcheck(resolved: ResolvedAuth): Promise<Result> {
  const h = await createTestHarness((server) => registerHealthcheckTools(server, { resolved, configError: null }));
  const res = await h.client.callTool({ name: 'canvas_healthcheck', arguments: {} });
  await h.close?.();
  return parseToolResult<Result>(res as never);
}

const BASE = 'https://school.instructure.com';

describe('a CloudFront block reads as edge_blocked, not a rejected credential', () => {
  afterEach(() => vi.restoreAllMocks());

  it('on the probe itself (token mode)', async () => {
    const fetchMock = vi.spyOn(globalThis, 'fetch').mockResolvedValue(blocked());

    const r = await healthcheck({
      source: 'env',
      account: { mode: 'token', name: 'x', baseUrl: BASE, token: 'tok' },
    });

    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('edge_blocked');
    expect(fetchMock).toHaveBeenCalledTimes(1);
  });

  it('on the session login the probe triggers (session mode)', async () => {
    // No session yet, so the probe first fetches the login page — and
    // CloudFront blocks that. Same edge, same page, one call earlier.
    vi.spyOn(globalThis, 'fetch').mockResolvedValue(blocked());

    const r = await healthcheck({
      source: 'env',
      account: { mode: 'session', name: 'x', baseUrl: BASE, username: 'u', password: 'p' },
    });

    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('edge_blocked');
  });

  it('control: a 403 with Canvas\'s own JSON is not called a block', async () => {
    vi.spyOn(globalThis, 'fetch').mockResolvedValue(
      new Response(JSON.stringify({ status: 'unauthorized', errors: [{ message: 'user not authorized to perform that action' }] }), {
        status: 403,
        statusText: 'Forbidden',
        headers: { 'content-type': 'application/json' },
      }),
    );

    const r = await healthcheck({
      source: 'env',
      account: { mode: 'token', name: 'x', baseUrl: BASE, token: 'tok' },
    });

    expect(r.ok).toBe(false);
    expect(r.error?.kind).not.toBe('edge_blocked');
  });
});
